### ISSUE TITLE
Sugestão de recursos

### ISSUE THREAD

**Issue by tgmarinho** [iuricode/recursos-gratuitos#1]
Oi Iuri, da hora o projeto.

Considere dar uma olhada nesses Links:

https://blog.rocketseat.com.br/melhores-sites-para-baixar-imagens-gratuitas-e-outros-recursos-2/

[]'s

**Comment by iuricode** [comment]
caraca show de bola! vou ver cada site desse link dar um atualizada no
repo, valeu!

Em sex., 28 de ago. de 2020 às 19:28, Thiago Marinho <
notifications@github.com> escreveu:
