### ISSUE TITLE
Não consegui fazer PR

### ISSUE THREAD

**Issue by HenriqueBaetaLeite** [iuricode/recursos-gratuitos#28]
Olá, gostaria de sugerir a inclusão de 2 links. Não sei o que fiz de errado, mas não consegui mandar um PR aqui...

Os links são do site Piskel. Um editor e criador de sprites voltado para games. Onde é possível exportar imagens e animações.
https://www.piskelapp.com/

O outro é o favpng. Imagens PNG gratuitas.
https://favpng.com/

**Comment by iuricode** [comment]
muito obrigado pela sugestão, em um futuro próximo iremos adicionar eles!
