### ISSUE TITLE
Links quebrados

### ISSUE THREAD

**Issue by arturjoaquim** [iuricode/recursos-gratuitos#31]
Em `recursos-gratuitos>Materiais Gratuitos Para Estudos>Livros` os seguintes links estão quebrados:

* [Apostila HTML, XHTML E CSS](https://github.com/walysonfelipe/ebooks/blob/main/HTML/HTML%20and%20CSS%20design%20and%20build%20websites.pdf)
* [HTML and CSS design and build websites](https://github.com/walysonfelipe/ebooks/blob/main/HTML/HTML%20and%20CSS%20design%20and%20build%20websites.pdf)
* [HTML5 e CSS3 com farinha e pimenta](https://drive.google.com/file/d/1LPUaSmTQmP1HM1qcd0BvqLQKWgG57cD_/view?usp=sharing)
* [HTML5](https://drive.google.com/file/d/1QSU3Pl4U5kVL8fiHbl_n1F2zfbOjRzek/view?usp=sharing)

**Muito obrigado pela iniciativa, abraços!**

**Comment by iuricode** [comment]
muito obrigado pelo aviso!
