### ISSUE TITLE
Como Contribuir com o Projeto? 

### ISSUE THREAD

**Issue by LeandroDukievicz** [iuricode/recursos-gratuitos#58]
Opa Iuri, gostaria de compartilhar um pouco do que aprendi e participar do projeto, faço um pull request com o um template readme explicando os pontos ? poderia explicar um pouco mais ?

**Comment by iuricode** [comment]
Olá Leandro, você pode ajudar a comunidade adicionando novos links, ou também verificar se os links estão certos (caso tenha algum fora de ar ou de lugar).

Link para mais informações sobre contribuição: https://github.com/iuricode/recursos-gratuitos/blob/main/CONTRIBUTING.md
