### ISSUE TITLE
Opção de Ilustrações - Abstrakt não está disponível

### ISSUE THREAD

**Issue by Maracujacake** [iuricode/recursos-gratuitos#78]
Ao abrir a opção **'Abstrakt'** no índice de **Ilustrações**, a seguinte página é mostrada: 

![image](https://github.com/iuricode/recursos-gratuitos/assets/74564883/7b1a97ce-cfde-4c47-840c-44ba45879de6)

Tanto pelo site hospedado na vercel quanto pelo próprio repositório o resultado foi o mesmo.

Não sei se cancelaram o site ou mudaram de endereço, mas estes parecem ser similares: https://www.behance.net/gallery/84803719/abstraktdesign-abstract-illustrations
https://www.instagram.com/abstraktdesign_/

**Comment by iuricode** [comment]
Olá Christian, agradeço sinceramente pelo seu feedback!

Após uma verificação nos links do repositório, identifiquei e corrigi mais de 30 links que levavam a páginas 404. Além disso, procedi à remoção de links sem protocolo HTTPS e corrigi aqueles que estavam erroneamente posicionados em tabelas. 

Sua contribuição relatando o erro foi fundamental para aprimorar o projeto. Agradeço novamente pela sua atenção e colaboração!
