### ISSUE TITLE
O que acha de criar um Readme de cursos por linguagem?

### ISSUE THREAD

**Issue by SuhMoraes** [iuricode/recursos-gratuitos#84]
Olá Iuri tudo bem?

Sei que o foco da page do github é voltado para Frontend, mas seria super legal e mais visual criar um readme com cursos por linguagem.

O que você acha?

**Comment by iuricode** [comment]
Olá, tudo bem sim e com você?

Irei criar um novo respositório essa semana para separar os recursos (imagens, fontes, logos, cores...) dos materiais (cursos, livros, eventos, podcasts...).
