### ISSUE TITLE
✨ feat: animação com js / frameworks

### ISSUE THREAD

**Issue by okayosilva** [iuricode/recursos-gratuitos#85]
Salve cria, vou listar algumas ferramentas de animações que são bem úteis para o desenvolvimento! 
Caso tenha alguma dúvida fico disponível para contato. 

Animações

[Swiper](https://swiperjs.com/) 
[barba](https://barba.js.org/)  [slick](https://kenwheeler.github.io/slick/) 
[Particles](https://vincentgarreau.com/particles.js/) 
[Tilt](https://gijsroge.github.io/tilt.js/) 
[GSAP](https://gsap.com/) 
[mo.js](https://mojs.github.io/) 
[shadcn](https://ui.shadcn.com/) 

Abraços!

**Comment by iuricode** [comment]
Olá!

Agradeço demais por listar essas ferramentas, irei adicionar um novo tópico no projeto para incluir essas e outras formas para criar animações.

**Comment by okayosilva** [comment]
Opa eu que agradeço por poder fazer parte e ajudar o projeto!

**Comment by okayosilva** [comment]
Abri um pull request com as ferramentas ja adicionadas, depois olha lá, tmj!
